import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Link } from "react-router-dom";
import { ChevronDown, Laptop, MapPin, Users, Layers, Clock, CalendarClock } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { ProgressBar } from "@/components/ui/ProgressBar";
import Button from "@/components/ui/Button";
import { courses, batchesForCourse, courseModes, totalTraineesForCourse, traineesForBatch } from "@/data/mockData";
import { cn } from "@/lib/utils";
export default function MyCourses() {
    const [openId, setOpenId] = useState(courses[0]?.id ?? null);
    return (_jsx("div", { className: "space-y-8", children: _jsx("div", { className: "rounded-3xl bg-[#FAF7F5] p-3 sm:p-4", children: _jsx("div", { className: "space-y-3", children: courses.map((c) => {
                    const isOpen = openId === c.id;
                    const courseBatches = batchesForCourse(c.id);
                    return (_jsxs("div", { className: "overflow-hidden rounded-2xl border border-[#F0EAE6] bg-white shadow-sm shadow-black/[0.02]", children: [_jsxs("button", { onClick: () => setOpenId(isOpen ? null : c.id), className: "flex w-full items-center justify-between gap-4 px-6 py-5 text-left", children: [_jsxs("span", { className: "flex items-center gap-3 min-w-0", children: [_jsx(ChevronDown, { className: cn("h-5 w-5 shrink-0 text-[#DE896A] transition-transform duration-200", isOpen && "rotate-180") }), _jsx("span", { className: "flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-[#FFFBF9] p-1", children: _jsx("img", { src: c.image, alt: "", className: "h-full w-full object-contain" }) }), _jsxs("span", { className: "truncate text-lg font-bold text-[#233047]", children: [c.name, " - ", c.level] })] }), _jsxs("span", { className: "shrink-0 whitespace-nowrap text-sm font-semibold text-[#DE896A]", children: [c.domains, " Domains \u2022 ", c.hours, " hrs"] })] }), isOpen && (_jsx("div", { className: "border-t border-[#F0EAE6] px-6 py-5", children: _jsxs("div", { className: "flex flex-col-reverse gap-6 md:flex-row md:items-start", children: [_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [courseModes(c.id).map((mode) => (_jsxs(Badge, { tone: mode === "online" ? "blue" : "amber", children: [mode === "online" ? _jsx(Laptop, { className: "h-3 w-3" }) : _jsx(MapPin, { className: "h-3 w-3" }), mode] }, mode))), _jsxs(Badge, { tone: "neutral", children: [totalTraineesForCourse(c.id), " trainees across ", courseBatches.length, " batch", courseBatches.length === 1 ? "" : "es"] })] }), _jsx("p", { className: "mt-3 text-xs text-[#B7A79D]", children: "Same curriculum, run independently \u2014 each batch below has its own trainees, its own pace, and (for offline batches) its own attendance." }), _jsx("div", { className: "mt-4 space-y-2.5", children: courseBatches.map((b) => {
                                                        const batchTrainees = traineesForBatch(b.id);
                                                        return (_jsxs("div", { className: "rounded-xl border border-[#F0EAE6] bg-[#FFFBF9] p-3.5", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-2", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-sm font-semibold text-[#3A2A22]", children: b.code }), _jsx("span", { className: "text-xs text-[#B7A79D]", children: b.label }), _jsxs(Badge, { tone: b.mode === "online" ? "blue" : "amber", className: "scale-90 origin-left", children: [b.mode === "online" ? _jsx(Laptop, { className: "h-3 w-3" }) : _jsx(MapPin, { className: "h-3 w-3" }), b.mode] })] }), _jsxs(Link, { to: b.mode === "offline" ? "/attendance" : "/trainees", state: { batchId: b.id }, className: "text-xs font-medium text-[#DE896A] hover:underline", children: [b.mode === "offline" ? "Mark Attendance" : "View Progress", " \u2192"] })] }), b.location && (_jsxs("p", { className: "mt-1.5 flex items-center gap-1.5 text-xs text-[#8C7A70]", children: [_jsx(MapPin, { className: "h-3.5 w-3.5" }), " ", b.location] })), _jsxs("div", { className: "mt-2.5 flex flex-wrap items-center gap-x-4 gap-y-1.5 text-xs text-[#8C7A70]", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Users, { className: "h-3.5 w-3.5 text-[#DE896A]" }), " ", batchTrainees.length, " trainees"] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(CalendarClock, { className: "h-3.5 w-3.5 text-[#DE896A]" }), " ", b.nextSession] })] }), _jsxs("div", { className: "mt-2.5", children: [_jsxs("div", { className: "flex items-center justify-between text-[11px] text-[#8C7A70]", children: [_jsx("span", { children: "Batch progress" }), _jsxs("span", { className: "font-semibold text-[#3A2A22]", children: [b.progress, "%"] })] }), _jsx(ProgressBar, { value: b.progress, className: "mt-1" })] })] }, b.id));
                                                    }) }), _jsxs("div", { className: "mt-4 grid grid-cols-2 gap-2 text-center sm:max-w-xs", children: [_jsxs("div", { className: "rounded-lg bg-[#FFFBF9] p-2", children: [_jsx(Layers, { className: "mx-auto h-4 w-4 text-[#DE896A]" }), _jsx("p", { className: "mt-1 text-sm font-semibold text-[#3A2A22]", children: c.domains }), _jsx("p", { className: "text-[10px] text-[#B7A79D]", children: "Domains" })] }), _jsxs("div", { className: "rounded-lg bg-[#FFFBF9] p-2", children: [_jsx(Clock, { className: "mx-auto h-4 w-4 text-[#DE896A]" }), _jsx("p", { className: "mt-1 text-sm font-semibold text-[#3A2A22]", children: c.hours }), _jsx("p", { className: "text-[10px] text-[#B7A79D]", children: "Hours" })] })] }), _jsx("div", { className: "mt-5 max-w-md", children: _jsx(Link, { to: `/content/modules?courseId=${c.id}`, children: _jsx(Button, { size: "sm", children: "Manage Content" }) }) })] }), _jsx("div", { className: "mx-auto w-40 shrink-0 overflow-hidden rounded-2xl bg-[#FFFBF9] sm:w-48 md:mx-0", children: _jsx("img", { src: c.image, alt: `${c.name} — ${c.level}`, className: "h-full w-full object-contain" }) })] }) }))] }, c.id));
                }) }) }) }));
}
